---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: synpro.grmlconfig
      vars:
        username: "root"

    - role: synpro.grmlconfig
      vars:
        username: "root"
        grmlconfig_groupname: "root"
