---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: lmde4
    image: linuxmintd/lmde4-amd64
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
